// <auto-generated />
using System;
using LordsOfTheFallenCharacterCreation.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CharacterCreater.Migrations
{
    [DbContext(typeof(CharacterContext))]
    [Migration("20251125190038_inital")]
    partial class inital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LordsOfTheFallenCharacterCreation.Models.Ancestry", b =>
                {
                    b.Property<int>("AncestryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AncestryId"));

                    b.Property<string>("AncestryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AncestryId");

                    b.ToTable("Acestrys");

                    b.HasData(
                        new
                        {
                            AncestryId = 1,
                            AncestryName = "Elf"
                        },
                        new
                        {
                            AncestryId = 2,
                            AncestryName = "Dwarf"
                        },
                        new
                        {
                            AncestryId = 3,
                            AncestryName = "Halfling"
                        },
                        new
                        {
                            AncestryId = 4,
                            AncestryName = "Gnome"
                        },
                        new
                        {
                            AncestryId = 5,
                            AncestryName = "Human"
                        },
                        new
                        {
                            AncestryId = 6,
                            AncestryName = "Half-elf"
                        });
                });

            modelBuilder.Entity("LordsOfTheFallenCharacterCreation.Models.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterId"));

                    b.Property<int?>("Agility")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("AncestryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("ClassId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Endurance")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Inferno")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Level")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Radiance")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Strength")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Vitality")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("CharacterId");

                    b.HasIndex("AncestryId");

                    b.HasIndex("ClassId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            Agility = 8,
                            AncestryId = 5,
                            ClassId = 1,
                            Endurance = 16,
                            FirstName = "Radiant",
                            Inferno = 8,
                            LastName = "Paladin",
                            Level = 51,
                            Radiance = 34,
                            Strength = 13,
                            Vitality = 26
                        },
                        new
                        {
                            CharacterId = 2,
                            Agility = 13,
                            AncestryId = 2,
                            ClassId = 8,
                            Endurance = 12,
                            FirstName = "Seismic",
                            Inferno = 35,
                            LastName = "Sorcerer",
                            Level = 42,
                            Radiance = 8,
                            Strength = 8,
                            Vitality = 20
                        },
                        new
                        {
                            CharacterId = 3,
                            Agility = 13,
                            AncestryId = 6,
                            ClassId = 9,
                            Endurance = 13,
                            FirstName = "Death",
                            Inferno = 22,
                            LastName = "Knight",
                            Level = 54,
                            Radiance = 22,
                            Strength = 13,
                            Vitality = 25
                        });
                });

            modelBuilder.Entity("LordsOfTheFallenCharacterCreation.Models.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<int?>("InitalAgility")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("InitalEndurance")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("InitalInferno")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("InitalLevel")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("InitalRadiance")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("InitalStrength")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("InitalVitality")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClassId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            ClassId = 1,
                            InitalAgility = 8,
                            InitalEndurance = 15,
                            InitalInferno = 8,
                            InitalLevel = 10,
                            InitalRadiance = 9,
                            InitalStrength = 12,
                            InitalVitality = 11,
                            Name = "Hallowed Knight"
                        },
                        new
                        {
                            ClassId = 2,
                            InitalAgility = 10,
                            InitalEndurance = 13,
                            InitalInferno = 8,
                            InitalLevel = 12,
                            InitalRadiance = 8,
                            InitalStrength = 16,
                            InitalVitality = 10,
                            Name = "Udirangr Warwolf"
                        },
                        new
                        {
                            ClassId = 3,
                            InitalAgility = 12,
                            InitalEndurance = 12,
                            InitalInferno = 8,
                            InitalLevel = 12,
                            InitalRadiance = 8,
                            InitalStrength = 13,
                            InitalVitality = 12,
                            Name = "Partisan"
                        },
                        new
                        {
                            ClassId = 4,
                            InitalAgility = 14,
                            InitalEndurance = 12,
                            InitalInferno = 8,
                            InitalLevel = 12,
                            InitalRadiance = 8,
                            InitalStrength = 12,
                            InitalVitality = 11,
                            Name = "Mournstead Infantry"
                        },
                        new
                        {
                            ClassId = 5,
                            InitalAgility = 13,
                            InitalEndurance = 11,
                            InitalInferno = 8,
                            InitalLevel = 8,
                            InitalRadiance = 8,
                            InitalStrength = 11,
                            InitalVitality = 10,
                            Name = "Blackfeather Ranger"
                        },
                        new
                        {
                            ClassId = 6,
                            InitalAgility = 16,
                            InitalEndurance = 11,
                            InitalInferno = 8,
                            InitalLevel = 10,
                            InitalRadiance = 8,
                            InitalStrength = 9,
                            InitalVitality = 11,
                            Name = "Exiled Stalker"
                        },
                        new
                        {
                            ClassId = 7,
                            InitalAgility = 8,
                            InitalEndurance = 9,
                            InitalInferno = 8,
                            InitalLevel = 11,
                            InitalRadiance = 18,
                            InitalStrength = 10,
                            InitalVitality = 11,
                            Name = "Orian Preacher"
                        },
                        new
                        {
                            ClassId = 8,
                            InitalAgility = 8,
                            InitalEndurance = 11,
                            InitalInferno = 18,
                            InitalLevel = 10,
                            InitalRadiance = 8,
                            InitalStrength = 9,
                            InitalVitality = 9,
                            Name = "Pyric Cultist"
                        },
                        new
                        {
                            ClassId = 9,
                            InitalAgility = 9,
                            InitalEndurance = 9,
                            InitalInferno = 9,
                            InitalLevel = 1,
                            InitalRadiance = 9,
                            InitalStrength = 9,
                            InitalVitality = 9,
                            Name = "Condemned"
                        });
                });

            modelBuilder.Entity("LordsOfTheFallenCharacterCreation.Models.Character", b =>
                {
                    b.HasOne("LordsOfTheFallenCharacterCreation.Models.Ancestry", "Ancestry")
                        .WithMany()
                        .HasForeignKey("AncestryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LordsOfTheFallenCharacterCreation.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ancestry");

                    b.Navigation("Class");
                });
#pragma warning restore 612, 618
        }
    }
}
